# Usa una imagen base de Python
FROM python:3.9-slim

# Copia el script de pruebasUDP.py al directorio de trabajo del contenedor
COPY pruebasUDP.py /app/pruebasUDP.py

# Establece el directorio de trabajo
WORKDIR /app

# Ejecuta el script de pruebasUDP.py
CMD ["python", "pruebasUDP.py"]
