FROM python:3.9-slim

# Copia el script del servidor UDP al contenedor
COPY server.py /app/server.py

# Establece el directorio de trabajo
WORKDIR /app

# Ejecuta el servidor UDP cuando se inicie el contenedor
CMD ["python", "server.py"]

