apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc2-deployment
  labels:
    app: tc2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tc2
  template:
    metadata:
      labels:
        app: tc2
    spec:
      containers:
        - name: tc2
          image: kevinqj19/tc2
          ports:
            - containerPort: 9666
---
apiVersion: v1
kind: Service
metadata:
  name: tc2-service
spec:
  selector:
    app: tc2
  ports:
    - name: http
      port: 9666
      targetPort: 9666
  type: LoadBalancer
